### ISSUE TITLE
Interesting resources and libraries

### ISSUE THREAD

**Issue by mpizenberg** [chouette-mail/chouette#9]
- email builder: https://github.com/lettre/lettre

**Comment by tforgione** [comment]
https://github.com/chouette-mail/chouette/blob/master/server/Cargo.toml#L27-L28 :smile: 
But thanks

**Comment by mpizenberg** [comment]
new email parser: https://github.com/stalwartlabs/mail-parser

**Comment by mpizenberg** [comment]
new mail delivery lib: https://github.com/stalwartlabs/mail-send
